sudo: false
language: android
env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_EMU_TGT=android-19
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_BUILD_TOOLS="28.0.3"
android:
  components:
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - ${ANDROID_EMU_TGT}
    - sys-img-${ANDROID_ABI}-${ANDROID_EMU_TGT}
  licenses:
    - '.+'
    
before_install:
  - yes | sdkmanager "platforms;${ANDROID_TARGET}"
  - yes | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
  
before_script:
  - chmod +x gradlew
script:
  - echo no | android create avd --force -n test -t $ANDROID_EMU_TGT --abi $ANDROID_ABI
  - QEMU_AUDIO_DRV=none emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb logcat BehaviorCountDownTimer:D BCDTTest:D *:S > logcat.log &
  - LOGCAT_PID=$!
  - ./gradlew build connectedCheck cAT
  - cat logcat.log
  - kill $LOGCAT_PID
